import { useState } from 'react'
import { screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { axe } from 'jest-axe'
import { renderK } from '../test/renderK'
import type { Scalar } from '../filters/types'
import { MultiSelect, type MultiSelectProps } from './MultiSelect'

const OPTS = [{ value: 'IN_WORK', label: 'В работе' }, { value: 'ERROR', label: 'Ошибка' }, { value: 'DEFERRED', label: 'Отложенный' }, { value: 'REJECTED', label: 'Отказ' }]

function Host({ initial = [], onValue = () => {}, ...p }: Partial<MultiSelectProps> & { initial?: Scalar[]; onValue?: (v: Scalar[]) => void }) {
  const [v, setV] = useState<Scalar[]>(initial)
  return <MultiSelect aria-label="Статус" options={OPTS} {...p} value={v} onChange={(x) => { setV(x); onValue(x) }} />
}

describe('MultiSelect', () => {
  it('поповер с поиском и списком; выбор в порядке справочника; список не закрывается', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    const trigger = screen.getByRole('button', { name: 'Статус: Не выбрано' })
    await u.click(trigger)
    const dialog = screen.getByRole('dialog', { name: 'Статус' })
    expect(within(dialog).getByRole('combobox', { name: 'Поиск: Статус' })).toHaveFocus()
    expect(within(dialog).getByRole('listbox')).toHaveAttribute('aria-multiselectable', 'true')
    await u.click(within(dialog).getByRole('option', { name: 'Отказ' }))
    await u.click(within(dialog).getByRole('option', { name: 'Ошибка' }))
    expect(onValue).toHaveBeenLastCalledWith(['ERROR', 'REJECTED'])
    expect(within(dialog).getByRole('option', { name: 'Ошибка' })).toHaveAttribute('aria-selected', 'true')
    expect(within(dialog).getByText('Выбрано 2')).toBeInTheDocument()
  })
  it('клавиатура в поиске: ввод, стрелка, Enter переключает', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.keyboard('отк')
    await u.keyboard('{ArrowDown}{Enter}')
    expect(onValue).toHaveBeenLastCalledWith(['REJECTED'])
  })
  it('чипы: два первых и «+N»; ✕ снимает значение, «Очистить» — все', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['IN_WORK', 'ERROR', 'REJECTED']} onValue={onValue} />)
    expect(screen.getByText('+1')).toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Убрать: В работе' }))
    expect(onValue).toHaveBeenLastCalledWith(['ERROR', 'REJECTED'])
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.click(screen.getByRole('button', { name: 'Очистить' }))
    expect(onValue).toHaveBeenLastCalledWith([])
  })
  it('max = 1: выбор заменяет выбранный', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['ERROR']} max={1} onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.click(screen.getByRole('option', { name: 'Отказ' }))
    expect(onValue).toHaveBeenLastCalledWith(['REJECTED'])
  })
  it('значение не из справочника сохраняется в конце', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['LEGACY']} onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.click(screen.getByRole('option', { name: 'Ошибка' }))
    expect(onValue).toHaveBeenLastCalledWith(['ERROR', 'LEGACY'])
  })
  it('значение не из справочника видно чипом и снимается', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['LEGACY']} onValue={onValue} />)
    expect(screen.getByText('LEGACY')).toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Убрать: LEGACY' }))
    expect(onValue).toHaveBeenLastCalledWith([])
  })
  it('max = 3: сверх предела не выбирается, снять можно; в подвале «из 3»', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['IN_WORK', 'ERROR', 'DEFERRED']} max={3} onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    expect(screen.getByText('Выбрано 3 из 3')).toBeInTheDocument()
    await u.click(screen.getByRole('option', { name: 'Отказ' }))
    expect(onValue).not.toHaveBeenCalled()
    await u.click(screen.getByRole('option', { name: 'Ошибка' }))
    expect(onValue).toHaveBeenLastCalledWith(['IN_WORK', 'DEFERRED'])
    await u.click(screen.getByRole('option', { name: 'Отказ' }))
    expect(onValue).toHaveBeenLastCalledWith(['IN_WORK', 'DEFERRED', 'REJECTED'])
  })
  it('Backspace на закрытом поле снимает последний чип', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['IN_WORK', 'ERROR', 'REJECTED']} onValue={onValue} />)
    screen.getByRole('button', { name: /^Статус:/ }).focus()
    await u.keyboard('{Backspace}')
    expect(onValue).toHaveBeenLastCalledWith(['IN_WORK', 'ERROR'])
    await u.keyboard('{Backspace}{Backspace}{Backspace}')
    expect(onValue).toHaveBeenLastCalledWith([])
    expect(onValue).toHaveBeenCalledTimes(3)
  })
  it('Backspace в пустом поиске снимает последний чип, в непустом — стирает символ', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['IN_WORK', 'ERROR']} onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.keyboard('аб{Backspace}')
    expect(onValue).not.toHaveBeenCalled()
    expect(screen.getByRole('combobox', { name: 'Поиск: Статус' })).toHaveValue('а')
    await u.keyboard('{Backspace}{Backspace}')
    expect(onValue).toHaveBeenLastCalledWith(['IN_WORK'])
  })
  it('Пробел переключает активный пункт при пустом запросе; в запросе — обычный символ', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.keyboard('{ArrowDown} ')
    expect(onValue).toHaveBeenLastCalledWith(['ERROR'])
    await u.keyboard('в р')
    expect(onValue).toHaveBeenCalledTimes(1)
    expect(screen.getByRole('combobox', { name: 'Поиск: Статус' })).toHaveValue('в р')
  })
  it('ArrowDown на поле открывает поповер; Escape закрывает и возвращает фокус на поле; aria-controls только у открытого', async () => {
    const u = userEvent.setup()
    renderK(<Host />)
    const trigger = screen.getByRole('button', { name: /^Статус:/ })
    expect(trigger).toHaveAttribute('aria-expanded', 'false')
    expect(trigger).not.toHaveAttribute('aria-controls')
    trigger.focus()
    await u.keyboard('{ArrowDown}')
    const dialog = screen.getByRole('dialog', { name: 'Статус' })
    expect(trigger).toHaveAttribute('aria-expanded', 'true')
    expect(trigger).toHaveAttribute('aria-controls', dialog.id)
    await u.keyboard('{Escape}')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(trigger).toHaveFocus()
    expect(trigger).not.toHaveAttribute('aria-controls')
  })
  it('Tab и Shift+Tab ходят по кругу внутри поповера; Escape возвращает фокус на поле', async () => {
    const u = userEvent.setup()
    renderK(<Host initial={['ERROR']} />)
    const trigger = screen.getByRole('button', { name: /^Статус:/ })
    await u.click(trigger)
    const box = screen.getByRole('combobox', { name: 'Поиск: Статус' })
    await u.tab()
    expect(screen.getByRole('button', { name: 'Очистить' })).toHaveFocus()
    await u.tab()
    expect(box).toHaveFocus()
    await u.tab({ shift: true })
    expect(screen.getByRole('button', { name: 'Очистить' })).toHaveFocus()
    await u.keyboard('{Escape}')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(trigger).toHaveFocus()
  })
  it('пока выбрано ноль, «Очистить» отключена и круг Tab замкнут на поиске', async () => {
    const u = userEvent.setup()
    renderK(<Host />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    expect(screen.getByRole('button', { name: 'Очистить' })).toBeDisabled()
    await u.tab()
    expect(screen.getByRole('combobox', { name: 'Поиск: Статус' })).toHaveFocus()
  })
  it('«Очистить» оставляет поповер открытым, фокус — в поиске; Enter не отправляет форму', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    const onSubmit = vi.fn((e: { preventDefault: () => void }) => e.preventDefault())
    renderK(<form onSubmit={onSubmit}><Host initial={['ERROR']} onValue={onValue} /></form>)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.click(screen.getByRole('button', { name: 'Очистить' }))
    expect(onValue).toHaveBeenLastCalledWith([])
    expect(screen.getByRole('combobox', { name: 'Поиск: Статус' })).toHaveFocus()
    await u.keyboard('{Enter}')
    expect(onSubmit).not.toHaveBeenCalled()
  })
  it('поиск без результата — «Ничего не найдено», Enter ничего не делает', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    await u.keyboard('яяя{Enter}')
    expect(screen.getByRole('option')).toHaveTextContent('Ничего не найдено')
    expect(onValue).not.toHaveBeenCalled()
  })
  it('клик по рамке вне кнопок открывает и закрывает поповер; ✕ чипа список не открывает и возвращает фокус на поле', async () => {
    const u = userEvent.setup()
    renderK(<Host initial={['IN_WORK', 'ERROR']} />)
    const trigger = screen.getByRole('button', { name: /^Статус:/ })
    await u.click(screen.getByText('В работе'))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    await u.click(screen.getAllByText('В работе')[0]!)
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Убрать: Ошибка' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(trigger).toHaveFocus()
  })
  it('недоступное поле: без ✕ у чипов, кнопка отключена', () => {
    renderK(<Host initial={['ERROR']} disabled />)
    expect(screen.getByRole('button', { name: /^Статус:/ })).toBeDisabled()
    expect(screen.queryByRole('button', { name: /^Убрать/ })).not.toBeInTheDocument()
  })
  it('axe: закрыт и открыт', async () => {
    const u = userEvent.setup()
    const { container } = renderK(<Host initial={['ERROR']} />)
    expect(await axe(container)).toHaveNoViolations()
    await u.click(screen.getByRole('button', { name: /^Статус:/ }))
    // поповер портируется в корень KatranProvider внутри container
    expect(container).toContainElement(screen.getByRole('dialog', { name: 'Статус' }))
    expect(await axe(container)).toHaveNoViolations()
  })
})
