import { useState } from 'react'
import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { axe } from 'jest-axe'
import { renderK } from '../test/renderK'
import { TagInput, type TagInputProps } from './TagInput'

function Host({ initial = [], onValue = () => {}, onText = () => {}, ...p }: Partial<TagInputProps> & { initial?: string[]; onValue?: (v: string[]) => void; onText?: (t: string) => void }) {
  const [v, setV] = useState<string[]>(initial)
  const [t, setT] = useState('')
  return <TagInput aria-label="Номер документа" mode="values" {...p} value={v} onChange={(x) => { setV(x); onValue(x) }} text={t} onTextChange={(x) => { setT(x); onText(x) }} />
}
const chipsOf = (name: string) => within(screen.getByRole('list', { name })).getAllByRole('listitem').map((li) => li.firstChild?.textContent)
const chips = () => chipsOf('Номер документа')
const paste = (el: HTMLElement, text: string) => fireEvent.paste(el, { clipboardData: { getData: () => text } })

/** Поле с подсказками: список задаёт тест, владелец убирает его по onSuggestClose, как модель фильтров. */
function Suggest({ items = ['ЗАО «Василёк»', 'ООО «Ромашка»'], loading = false, initial = [], onQuery = () => {}, onSuggestClose = () => {}, onValue = () => {} }: {
  items?: string[]; loading?: boolean; initial?: string[]; onQuery?: (q: string) => void; onSuggestClose?: () => void; onValue?: (v: string[]) => void
}) {
  const [v, setV] = useState<string[]>(initial)
  const [t, setT] = useState('')
  const [shown, setShown] = useState(false)
  return (
    <TagInput aria-label="Приказодатель" mode="phrases" value={v} onChange={(x) => { setV(x); onValue(x) }} text={t} onTextChange={setT}
      suggestions={shown ? items : []} loading={shown && loading}
      onQuery={(q) => { setShown(q !== ''); onQuery(q) }} onSuggestClose={() => { setShown(false); onSuggestClose() }} />
  )
}

describe('TagInput: ввод значений', () => {
  it('values: пробел, запятая и Enter делают чипы; хвост остаётся в поле', async () => {
    const u = userEvent.setup()
    renderK(<Host />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    await u.type(input, '400 403,406')
    expect(chips()).toEqual(['400', '403'])
    expect(input).toHaveValue('406')
    await u.keyboard('{Enter}')
    expect(chips()).toEqual(['400', '403', '406'])
    expect(input).toHaveValue('')
  })
  it('values: разделители без значения в строке не остаются', async () => {
    const u = userEvent.setup()
    renderK(<Host />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    await u.type(input, ' ,;400')
    expect(input).toHaveValue('400')
    expect(screen.queryByRole('list', { name: 'Номер документа' })).not.toBeInTheDocument()
  })
  it('values: Tab делает чип и уводит фокус дальше', async () => {
    const u = userEvent.setup()
    renderK(<><Host /><button type="button">после</button></>)
    await u.type(screen.getByRole('textbox', { name: 'Номер документа' }), '400')
    await u.tab()
    expect(chips()).toEqual(['400'])
    expect(screen.getByRole('button', { name: 'после' })).toHaveFocus()
  })
  it('phrases: Tab не делит — фраза остаётся текстом', async () => {
    const u = userEvent.setup()
    const onText = vi.fn()
    renderK(<><Host aria-label="Назначение" mode="phrases" onText={onText} /><button type="button">после</button></>)
    await u.type(screen.getByRole('textbox', { name: 'Назначение' }), 'нет покрытия')
    await u.tab()
    expect(screen.queryByRole('list', { name: 'Назначение' })).not.toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: 'Назначение' })).toHaveValue('нет покрытия')
  })
  it('повтор не добавляется, текст очищается, скринридеру — «Уже есть»', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['400']} onValue={onValue} />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    await u.type(input, '400 ')
    expect(onValue).not.toHaveBeenCalled()
    expect(input).toHaveValue('')
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Уже есть: 400'))
  })
  it('добавление объявляется живой областью', async () => {
    const u = userEvent.setup()
    renderK(<Host />)
    await u.type(screen.getByRole('textbox', { name: 'Номер документа' }), '400,')
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Добавлено: 400'))
  })
  it('phrases: две фразы в кавычках и Enter — два чипа', async () => {
    const u = userEvent.setup()
    renderK(<Host aria-label="Назначение" mode="phrases" />)
    const input = screen.getByRole('textbox', { name: 'Назначение' })
    await u.type(input, '"счёт не найден" "инструкция инвалидна"{Enter}')
    expect(chipsOf('Назначение')).toEqual(['счёт не найден', 'инструкция инвалидна'])
  })
  it('phrases: ; делит, запятая и пробел — часть фразы; ; внутри открытой кавычки не делит', async () => {
    const u = userEvent.setup()
    renderK(<Host aria-label="Назначение" mode="phrases" />)
    const input = screen.getByRole('textbox', { name: 'Назначение' })
    await u.type(input, 'Оплата, НДС 20 %;')
    expect(chipsOf('Назначение')).toEqual(['Оплата, НДС 20 %'])
    await u.type(input, '"a; b')
    expect(input).toHaveValue('"a; b')
    expect(chipsOf('Назначение')).toEqual(['Оплата, НДС 20 %'])
    await u.keyboard('{Enter}')
    expect(chipsOf('Назначение')).toEqual(['Оплата, НДС 20 %', 'a; b'])
  })
  it('phrases: набор «ООО «Ромашка»» и Enter — один чип с кавычками; «a» «b» — два', async () => {
    const u = userEvent.setup()
    renderK(<Host aria-label="Назначение" mode="phrases" />)
    const input = screen.getByRole('textbox', { name: 'Назначение' })
    await u.type(input, 'ООО «Ромашка»{Enter}')
    expect(chipsOf('Назначение')).toEqual(['ООО «Ромашка»'])
    await u.type(input, '«a» «b»{Enter}')
    expect(chipsOf('Назначение')).toEqual(['ООО «Ромашка»', 'a', 'b'])
  })
  it('IME: во время набора разделитель не делит, по окончании набора — делит', () => {
    renderK(<Host />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    fireEvent.compositionStart(input)
    fireEvent.change(input, { target: { value: '400 40' } })
    expect(screen.queryByRole('list', { name: 'Номер документа' })).not.toBeInTheDocument()
    expect(input).toHaveValue('400 40')
    fireEvent.compositionEnd(input)
    expect(chips()).toEqual(['400'])
    expect(input).toHaveValue('40')
  })
  it('Enter с пустым текстом не перехватывается — форма отправляется', async () => {
    const u = userEvent.setup()
    const onSubmit = vi.fn((e: { preventDefault: () => void }) => e.preventDefault())
    renderK(<form onSubmit={onSubmit}><Host initial={['400']} /></form>)
    await u.type(screen.getByRole('textbox', { name: 'Номер документа' }), '401{Enter}')
    expect(onSubmit).not.toHaveBeenCalled()
    await u.keyboard('{Enter}')
    expect(onSubmit).toHaveBeenCalledTimes(1)
  })
})

describe('TagInput: вставка', () => {
  it('колонка из Excel — чип на строку', () => {
    renderK(<Host />)
    paste(screen.getByRole('textbox', { name: 'Номер документа' }), '400\r\n403\r\n406\r\n')
    expect(chips()).toEqual(['400', '403', '406'])
  })
  it('строка из Excel (табуляция) и набранный текст до вставки — одно целое', async () => {
    const u = userEvent.setup()
    renderK(<Host />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    await u.type(input, '12')
    paste(input, '3\t404\t405')
    expect(chips()).toEqual(['123', '404', '405'])
    expect(input).toHaveValue('')
  })
  it('вставка без разделителя — обычная вставка текстом, не чип', () => {
    renderK(<Host />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    expect(paste(input, '400')).toBe(true)
    expect(screen.queryByRole('list', { name: 'Номер документа' })).not.toBeInTheDocument()
  })
  it('phrases: вставка фраз в кавычках и строк; незакрытая кавычка закрывается концом', () => {
    renderK(<Host aria-label="Назначение" mode="phrases" />)
    const input = screen.getByRole('textbox', { name: 'Назначение' })
    paste(input, '"счёт не найден" "инструкция инвалидна"')
    expect(chipsOf('Назначение')).toEqual(['счёт не найден', 'инструкция инвалидна'])
    paste(input, 'нет покрытия\r\n"лимит; превышен')
    expect(chipsOf('Назначение')).toEqual(['счёт не найден', 'инструкция инвалидна', 'нет покрытия', 'лимит; превышен'])
  })
  it('phrases: вставка «ООО «Ромашка»» — текстом, Enter — один чип; вставка двух наименований через ; — два чипа; «a» «b» — два', async () => {
    const u = userEvent.setup()
    renderK(<Host aria-label="Назначение" mode="phrases" />)
    const input = screen.getByRole('textbox', { name: 'Назначение' })
    expect(paste(input, 'ООО «Ромашка»')).toBe(true)
    await u.type(input, 'ООО «Ромашка»{Enter}')
    expect(chipsOf('Назначение')).toEqual(['ООО «Ромашка»'])
    paste(input, 'ЗАО «Василёк»; АО «Лютик»')
    expect(chipsOf('Назначение')).toEqual(['ООО «Ромашка»', 'ЗАО «Василёк»', 'АО «Лютик»'])
    paste(input, '«a» «b»')
    expect(chipsOf('Назначение')).toEqual(['ООО «Ромашка»', 'ЗАО «Василёк»', 'АО «Лютик»', 'a', 'b'])
  })
  it('phrases: повтор без учёта регистра не добавляется', () => {
    renderK(<Host aria-label="Назначение" mode="phrases" initial={['Отказ']} />)
    paste(screen.getByRole('textbox', { name: 'Назначение' }), 'отказ;ошибка')
    expect(chipsOf('Назначение')).toEqual(['Отказ', 'ошибка'])
  })
  it('предел: лишние не добавляются, строка о пределе под полем описывает поле и объявляется', async () => {
    renderK(<Host max={2} />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    paste(input, '1 2 3 4')
    expect(chips()).toEqual(['1', '2'])
    expect(screen.getByText('Добавлено 2 из 4: больше нельзя', { selector: 'span' })).toBeInTheDocument()
    expect(input).toHaveAccessibleDescription('1 2 Добавлено 2 из 4: больше нельзя')
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Добавлено 2 из 4: больше нельзя'))
  })
  it('предел: набранное сверх предела остаётся текстом; снятие чипа убирает строку о пределе', async () => {
    const u = userEvent.setup()
    renderK(<Host max={2} initial={['1', '2']} />)
    const input = screen.getByRole('textbox', { name: 'Номер документа' })
    await u.type(input, '3{Enter}')
    expect(input).toHaveValue('3')
    expect(screen.getByText('Не добавлено: предел 2', { selector: 'span' })).toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Убрать: 1' }))
    expect(screen.queryByText('Не добавлено: предел 2', { selector: 'span' })).not.toBeInTheDocument()
  })
  it('предел по умолчанию для values — 500', () => {
    renderK(<Host />)
    paste(screen.getByRole('textbox', { name: 'Номер документа' }), Array.from({ length: 732 }, (_, i) => String(i + 1)).join('\n'))
    expect(screen.getAllByRole('listitem')).toHaveLength(500)
    expect(screen.getByText('Добавлено 500 из 732: больше нельзя', { selector: 'span' })).toBeInTheDocument()
  })
})

describe('TagInput: чипы', () => {
  it('Backspace: первый выделяет последний чип, второй снимает; ← и Delete', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['400', '403', '406']} onValue={onValue} />)
    screen.getByRole('textbox', { name: 'Номер документа' }).focus()
    await u.keyboard('{Backspace}')
    expect(screen.getAllByRole('listitem')[2]).toHaveAttribute('data-selected', 'true')
    expect(onValue).not.toHaveBeenCalled()
    await u.keyboard('{Backspace}')
    expect(onValue).toHaveBeenLastCalledWith(['400', '403'])
    await u.keyboard('{ArrowLeft}{ArrowLeft}{Delete}')
    expect(onValue).toHaveBeenLastCalledWith(['403'])
  })
  it('выделение объявляется; → за последним снимает выделение; Escape снимает; Delete без выделения ничего не снимает', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['400', '403']} onValue={onValue} />)
    screen.getByRole('textbox', { name: 'Номер документа' }).focus()
    await u.keyboard('{Delete}')
    expect(onValue).not.toHaveBeenCalled()
    await u.keyboard('{ArrowLeft}')
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Выделено: 403'))
    await u.keyboard('{ArrowRight}')
    expect(screen.getAllByRole('listitem')[1]).not.toHaveAttribute('data-selected')
    await u.keyboard('{ArrowLeft}{Escape}{Delete}')
    expect(onValue).not.toHaveBeenCalled()
  })
  it('снятие клавиатурой объявляется вместе с новым выделением', async () => {
    const u = userEvent.setup()
    renderK(<Host initial={['400', '403']} />)
    screen.getByRole('textbox', { name: 'Номер документа' }).focus()
    await u.keyboard('{Backspace}{Backspace}')
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Убрано: 403; выделено: 400'))
  })
  it('стрелки по чипам — только в пустой строке', async () => {
    const u = userEvent.setup()
    renderK(<Host initial={['400']} />)
    await u.type(screen.getByRole('textbox', { name: 'Номер документа' }), '5{ArrowLeft}{Backspace}')
    expect(screen.getAllByRole('listitem')[0]).not.toHaveAttribute('data-selected')
  })
  it('✕ у чипа снимает значение, фокус возвращается в строку ввода, снятие объявляется', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={['400', '403']} onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Убрать: 400' }))
    expect(onValue).toHaveBeenLastCalledWith(['403'])
    expect(screen.getByRole('textbox', { name: 'Номер документа' })).toHaveFocus()
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Убрано: 400'))
  })
  it('✕ не в порядке Tab', () => {
    renderK(<Host initial={['400']} />)
    expect(screen.getByRole('button', { name: 'Убрать: 400' })).toHaveAttribute('tabindex', '-1')
  })
  it('клик по рамке (подпись чипа) переводит фокус в строку ввода', async () => {
    const u = userEvent.setup()
    renderK(<Host initial={['400']} />)
    await u.click(screen.getByText('400'))
    expect(screen.getByRole('textbox', { name: 'Номер документа' })).toHaveFocus()
  })
  it('невалидное значение — красный чип с пометкой для скринридера', () => {
    renderK(<Host initial={['400', 'abc']} validate={(v) => /^\d+$/.test(v)} />)
    const bad = screen.getAllByRole('listitem')[1]!
    expect(bad).toHaveAttribute('data-invalid', 'true')
    expect(bad).toHaveTextContent('неверное значение')
    expect(screen.getAllByRole('listitem')[0]).not.toHaveAttribute('data-invalid')
  })
  it('строка ввода описана значениями чипов (первые 10 и «ещё N»), не кнопками ✕', () => {
    renderK(<Host initial={['400', 'abc']} validate={(v) => /^\d+$/.test(v)} />)
    expect(screen.getByRole('textbox', { name: 'Номер документа' })).toHaveAccessibleDescription('400 abc, неверное значение')
  })
  it('больше 10 чипов — в описании первые 10 и «ещё N»', () => {
    renderK(<Host initial={Array.from({ length: 12 }, (_, i) => String(i + 1))} />)
    expect(screen.getByRole('textbox', { name: 'Номер документа' })).toHaveAccessibleDescription('1 2 3 4 5 6 7 8 9 10 ещё 2')
  })
  it('повтор во внешнем значении не ломает список', () => {
    renderK(<Host initial={['400', '400']} />)
    expect(chips()).toEqual(['400', '400'])
  })
  it('недоступное поле: без ✕, строка ввода отключена', () => {
    renderK(<Host initial={['400']} disabled />)
    expect(screen.getByRole('textbox', { name: 'Номер документа' })).toBeDisabled()
    expect(screen.queryByRole('button', { name: /^Убрать/ })).not.toBeInTheDocument()
  })
  it('placeholder — только пока нет чипов', () => {
    const { rerender } = renderK(<TagInput aria-label="Номер" mode="values" value={[]} onChange={() => {}} text="" onTextChange={() => {}} placeholder="Номера через пробел" />)
    expect(screen.getByRole('textbox', { name: 'Номер' })).toHaveAttribute('placeholder', 'Номера через пробел')
    rerender(<TagInput aria-label="Номер" mode="values" value={['1']} onChange={() => {}} text="" onTextChange={() => {}} placeholder="Номера через пробел" />)
    expect(screen.getByRole('textbox', { name: 'Номер' })).not.toHaveAttribute('placeholder')
  })
})

describe('TagInput: подсказки', () => {
  it('комбобокс; список не открывается фокусом, открывается вводом; ↓ и Enter добавляют чип, закрытие сообщает onSuggestClose', async () => {
    const u = userEvent.setup()
    const onQuery = vi.fn()
    const onSuggestClose = vi.fn()
    renderK(<Suggest onQuery={onQuery} onSuggestClose={onSuggestClose} />)
    const box = screen.getByRole('combobox', { name: 'Приказодатель' })
    expect(box).toHaveAttribute('aria-autocomplete', 'list')
    await u.click(box)
    expect(onQuery).not.toHaveBeenCalled()
    expect(box).toHaveAttribute('aria-expanded', 'false')
    expect(box).not.toHaveAttribute('aria-controls')
    await u.type(box, 'ва')
    expect(onQuery).toHaveBeenLastCalledWith('ва')
    const list = screen.getByRole('listbox', { name: 'Подсказки: Приказодатель' })
    expect(box).toHaveAttribute('aria-expanded', 'true')
    expect(box).toHaveAttribute('aria-controls', list.id)
    expect(box).not.toHaveAttribute('aria-activedescendant')
    await u.keyboard('{ArrowDown}')
    expect(box).toHaveAttribute('aria-activedescendant', within(list).getAllByRole('option')[0]!.id)
    await u.keyboard('{Enter}')
    expect(chipsOf('Приказодатель')).toEqual(['ЗАО «Василёк»'])
    expect(box).toHaveValue('')
    expect(onSuggestClose).toHaveBeenCalled()
    expect(screen.queryByRole('listbox')).not.toBeInTheDocument()
  })
  it('Enter без активной подсказки делает чип из набранного', async () => {
    const u = userEvent.setup()
    renderK(<Suggest />)
    await u.type(screen.getByRole('combobox', { name: 'Приказодатель' }), 'ва{Enter}')
    expect(chipsOf('Приказодатель')).toEqual(['ва'])
  })
  it('клик по подсказке добавляет её; совпадение выделено полужирным', async () => {
    const u = userEvent.setup()
    renderK(<Suggest />)
    await u.type(screen.getByRole('combobox', { name: 'Приказодатель' }), 'ром')
    const opt = screen.getByRole('option', { name: 'ООО «Ромашка»' })
    expect(within(opt).getByText('Ром').tagName).toBe('B')
    fireEvent.click(opt)
    expect(chipsOf('Приказодатель')).toEqual(['ООО «Ромашка»'])
  })
  it('Escape закрывает список и сообщает onSuggestClose; ↓ открывает снова', async () => {
    const u = userEvent.setup()
    const onSuggestClose = vi.fn()
    const onQuery = vi.fn()
    renderK(<Suggest onSuggestClose={onSuggestClose} onQuery={onQuery} />)
    const box = screen.getByRole('combobox', { name: 'Приказодатель' })
    await u.type(box, 'ва')
    await u.keyboard('{Escape}')
    expect(screen.queryByRole('listbox')).not.toBeInTheDocument()
    expect(onSuggestClose).toHaveBeenCalledTimes(1)
    expect(box).toHaveValue('ва')
    await u.keyboard('{ArrowDown}')
    expect(onQuery).toHaveBeenLastCalledWith('ва')
    expect(screen.getByRole('listbox')).toBeInTheDocument()
  })
  it('загрузка без подсказок — «Ищу…»; пустой ответ — список закрыт', async () => {
    const u = userEvent.setup()
    const { rerender } = renderK(<Suggest items={[]} loading />)
    const box = screen.getByRole('combobox', { name: 'Приказодатель' })
    await u.type(box, 'ва')
    const list = screen.getByRole('listbox', { name: 'Подсказки: Приказодатель' })
    expect(within(list).getByRole('option')).toHaveTextContent('Ищу…')
    expect(within(list).getByRole('option')).toHaveAttribute('aria-disabled', 'true')
    await u.keyboard('{ArrowDown}{Enter}')
    expect(chipsOf('Приказодатель')).toEqual(['ва'])
    rerender(<Suggest items={[]} />)
    await u.type(box, 'ро')
    expect(screen.queryByRole('listbox')).not.toBeInTheDocument()
    expect(box).toHaveAttribute('aria-expanded', 'false')
  })
  it('подсказки, уже стоящие чипами, не показываются (фразы — без учёта регистра)', async () => {
    const u = userEvent.setup()
    renderK(<Suggest initial={['зао «василёк»']} />)
    await u.type(screen.getByRole('combobox', { name: 'Приказодатель' }), 'о')
    expect(screen.getAllByRole('option').map((o) => o.textContent)).toEqual(['ООО «Ромашка»'])
  })
  it('уход фокуса закрывает список', async () => {
    const u = userEvent.setup()
    const onSuggestClose = vi.fn()
    renderK(<><Suggest onSuggestClose={onSuggestClose} /><button type="button">после</button></>)
    await u.type(screen.getByRole('combobox', { name: 'Приказодатель' }), 'ва')
    await u.tab()
    expect(screen.queryByRole('listbox')).not.toBeInTheDocument()
    expect(onSuggestClose).toHaveBeenCalled()
  })
})

describe('TagInput: axe', () => {
  it('с чипами, невалидным значением и строкой о пределе', async () => {
    const { container } = renderK(<Host initial={['400', 'abc']} max={3} validate={(v) => /^\d+$/.test(v)} />)
    expect(await axe(container)).toHaveNoViolations()
    paste(screen.getByRole('textbox', { name: 'Номер документа' }), '1 2')
    expect(await axe(container)).toHaveNoViolations()
  })
  it('с открытыми подсказками и при загрузке', async () => {
    const u = userEvent.setup()
    const { container } = renderK(<Suggest initial={['АО «Лютик»']} />)
    await u.type(screen.getByRole('combobox', { name: 'Приказодатель' }), 'ва')
    // список портируется в корень KatranProvider внутри container
    expect(container).toContainElement(screen.getByRole('listbox'))
    await u.keyboard('{ArrowDown}')
    expect(await axe(container)).toHaveNoViolations()
  })
  it('при загрузке', async () => {
    const u = userEvent.setup()
    const { container } = renderK(<Suggest items={[]} loading />)
    await u.type(screen.getByRole('combobox', { name: 'Приказодатель' }), 'ва')
    expect(container).toContainElement(screen.getByRole('listbox'))
    expect(await axe(container)).toHaveNoViolations()
  })
})
