export { FxDocsPage } from './ui/FxDocsPage'
export { FX_LOCAL_TABS, detail, docLinkOpened, lifecycle } from './model/registry.model'
export { docActions } from './model/actions.model'
export { docEdit } from './model/edit.model'
export { fxDetailDomain } from './ui/detailDomain'
