import { useState } from 'react'
import { screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { axe } from 'jest-axe'
import { renderK } from '../test/renderK'
import { DateRange, type DateRangeProps, type DateRangeValue } from './DateRange'

const EMPTY: DateRangeValue = { from: '', to: '' }
function Host({ initial = EMPTY, onValue = () => {}, ...p }: Partial<DateRangeProps> & { initial?: DateRangeValue; onValue?: (v: DateRangeValue) => void }) {
  const [v, setV] = useState<DateRangeValue>(initial)
  return <DateRange label="Дата документа" today="2026-09-23" {...p} value={v} onChange={(x) => { setV(x); onValue(x) }} />
}

describe('DateRange', () => {
  it('два поля в группе; «по» раньше «с» — invalid, наружу только «с»', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    expect(screen.getByRole('group', { name: 'Дата документа' })).toBeInTheDocument()
    await u.type(screen.getByRole('textbox', { name: 'Дата документа, с' }), '10092026')
    await u.type(screen.getByRole('textbox', { name: 'Дата документа, по' }), '05092026')
    expect(screen.getByRole('textbox', { name: 'Дата документа, по' })).toHaveAttribute('aria-invalid', 'true')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10', to: '' })
  })
  it('горячие кнопки: «3 дня» — сегодня и два предыдущих, повторный клик снимает', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    const quick = screen.getByRole('group', { name: 'Дата документа: быстрый период' })
    expect(quick).toHaveTextContent('Сегодня')
    await u.click(screen.getByRole('button', { name: '3 дня' }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-21', to: '2026-09-23' })
    expect(screen.getByRole('button', { name: '3 дня' })).toHaveAttribute('aria-pressed', 'true')
    await u.click(screen.getByRole('button', { name: '3 дня' }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '', to: '' })
  })
  it('календарь: два клика в обратном порядке меняют границы местами и закрывают поповер', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(screen.getByRole('button', { name: /^10 сентября/ }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10', to: '' })
    await u.hover(screen.getByRole('button', { name: /^7 сентября/ }))
    expect(screen.getByRole('button', { name: /^8 сентября/ })).toHaveAttribute('data-in', 'true')
    await u.click(screen.getByRole('button', { name: /^7 сентября/ }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-07', to: '2026-09-10' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
  it('пресет в поповере ставит период и закрывает', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(screen.getByRole('button', { name: 'Прошлый месяц' }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-08-01', to: '2026-08-31' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
  it('со временем: время границ и «Готово»; поля показывают время', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host time onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(screen.getByRole('button', { name: /^1 сентября/ }))
    await u.click(screen.getByRole('button', { name: /^3 сентября/ }))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    await u.type(screen.getByRole('textbox', { name: 'Время с' }), '0930')
    await u.type(screen.getByRole('textbox', { name: 'Время по' }), '1800')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-01T09:30', to: '2026-09-03T18:00' })
    await u.click(screen.getByRole('button', { name: 'Готово' }))
    expect(screen.getByRole('textbox', { name: 'Дата документа, с' })).toHaveValue('01.09.2026 09:30')
  })
  it('со временем корень помечен data-time — по нему CSS держит минимальную ширину range-time-w', () => {
    const { unmount } = renderK(<Host time />)
    expect(screen.getByRole('group', { name: 'Дата документа' }).closest('[data-time]')).not.toBeNull()
    unmount()
    renderK(<Host />)
    expect(screen.getByRole('group', { name: 'Дата документа' }).closest('[data-time]')).toBeNull()
  })
  it('без горячих кнопок и пресетов', async () => {
    const u = userEvent.setup()
    renderK(<Host quick={[]} presets={[]} />)
    expect(screen.queryByRole('group', { name: 'Дата документа: быстрый период' })).not.toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    expect(screen.queryByRole('button', { name: 'Сегодня' })).not.toBeInTheDocument()
  })
  it('axe: закрыт и открыт', async () => {
    const u = userEvent.setup()
    const { container } = renderK(<Host initial={{ from: '2026-09-01', to: '2026-09-03' }} time />)
    expect(await axe(container)).toHaveNoViolations()
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    // поповер портируется в корень KatranProvider внутри container; axe(document.body) ловит страничное правило region
    expect(container).toContainElement(screen.getByRole('dialog'))
    expect(await axe(container)).toHaveNoViolations()
  })

  it('пресет в поповере со временем не закрывает: сначала можно дописать время', async () => {
    const u = userEvent.setup()
    renderK(<Host time />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: '7 дней' }))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: 'Время по' })).toBeEnabled()
  })
  it('время границы недоступно, пока у границы нет дня', async () => {
    const u = userEvent.setup()
    renderK(<Host time />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    expect(screen.getByRole('textbox', { name: 'Время с' })).toBeDisabled()
    expect(screen.getByRole('textbox', { name: 'Время по' })).toBeDisabled()
    await u.click(screen.getByRole('button', { name: /^1 сентября/ }))
    expect(screen.getByRole('textbox', { name: 'Время с' })).toBeEnabled()
    expect(screen.getByRole('textbox', { name: 'Время по' })).toBeDisabled()
    await u.click(screen.getByRole('button', { name: /^3 сентября/ }))
    expect(screen.getByRole('textbox', { name: 'Время по' })).toBeEnabled()
  })
  it('горячие кнопки и пресеты вне min/max недоступны, совпавший пресет отмечен', async () => {
    const u = userEvent.setup()
    renderK(<Host min="2026-09-23" max="2026-09-23" initial={{ from: '2026-09-23', to: '2026-09-23' }} />)
    expect(screen.getByRole('button', { name: 'Сегодня' })).toBeEnabled()
    expect(screen.getByRole('button', { name: 'Сегодня' })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('button', { name: 'Вчера' })).toBeDisabled()
    expect(screen.getByRole('button', { name: '3 дня' })).toBeDisabled()
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    const pop = within(screen.getByRole('dialog'))
    expect(pop.getByRole('button', { name: '7 дней' })).toBeDisabled()
    expect(pop.getByRole('button', { name: 'Прошлый месяц' })).toBeDisabled()
    expect(pop.getByRole('button', { name: 'Сегодня' })).toBeEnabled()
  })
  it('отмеченный пресет в поповере подсвечен по дням, время не мешает', async () => {
    const u = userEvent.setup()
    renderK(<Host time initial={{ from: '2026-09-21T09:00', to: '2026-09-23T18:00' }} />)
    expect(screen.getByRole('button', { name: '3 дня' })).toHaveAttribute('aria-pressed', 'true')
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    expect(within(screen.getByRole('dialog')).getByRole('button', { name: '3 дня' })).toHaveAttribute('aria-pressed', 'true')
  })
  it('«с» позже «по»: «по» сбрасывается, а не остаётся раньше «с»', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={{ from: '2026-09-01', to: '2026-09-03' }} onValue={onValue} />)
    const from = screen.getByRole('textbox', { name: 'Дата документа, с' })
    await u.clear(from)
    await u.type(from, '05092026')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-05', to: '' })
    expect(screen.getByRole('textbox', { name: 'Дата документа, по' })).toHaveValue('')
  })
  it('«по» в тот же день, что «с», допустимо', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={{ from: '2026-09-10', to: '' }} onValue={onValue} />)
    await u.type(screen.getByRole('textbox', { name: 'Дата документа, по' }), '10092026')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10', to: '2026-09-10' })
  })
  it('поповер: имя диалога, aria-controls только пока открыт, фокус возвращается в «с»', async () => {
    const u = userEvent.setup()
    renderK(<Host />)
    const btn = screen.getByRole('button', { name: 'Выбрать период' })
    expect(btn).not.toHaveAttribute('aria-controls')
    await u.click(btn)
    const dialog = screen.getByRole('dialog', { name: 'Дата документа: выбор периода' })
    expect(btn).toHaveAttribute('aria-controls', dialog.id)
    expect(dialog.id).not.toBe('')
    await u.keyboard('{Escape}')
    expect(dialog).not.toBeInTheDocument()
    expect(btn).not.toHaveAttribute('aria-controls')
    expect(document.activeElement).toBe(screen.getByRole('textbox', { name: 'Дата документа, с' }))
  })
  it('Escape посреди выбора сбрасывает ожидание второго дня', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(screen.getByRole('button', { name: /^10 сентября/ }))
    await u.keyboard('{Escape}')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(screen.getByRole('button', { name: /^20 сентября/ }))
    // после Escape ожидание сброшено: клик — снова первый, а не второй
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-20', to: '' })
    expect(screen.getByRole('dialog')).toBeInTheDocument()
  })

  it('«по» догоняет смену «с»: набранное и ставшее валидным уходит наружу', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={{ from: '2026-09-10', to: '' }} onValue={onValue} />)
    const from = screen.getByRole('textbox', { name: 'Дата документа, с' })
    const to = screen.getByRole('textbox', { name: 'Дата документа, по' })
    await u.type(to, '05092026')
    expect(to).toHaveAttribute('aria-invalid', 'true')
    expect(onValue).not.toHaveBeenCalled()
    await u.clear(from)
    await u.type(from, '01092026')
    expect(to).not.toHaveAttribute('aria-invalid')
    expect(to).toHaveValue('05.09.2026')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-01', to: '2026-09-05' })
  })
  it('валидное «по», затем «с» позже него: «по» сбрасывается и поле пустое', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host initial={{ from: '2026-09-01', to: '' }} onValue={onValue} />)
    const from = screen.getByRole('textbox', { name: 'Дата документа, с' })
    const to = screen.getByRole('textbox', { name: 'Дата документа, по' })
    await u.type(to, '05092026')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-01', to: '2026-09-05' })
    await u.clear(from)
    await u.type(from, '10092026')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10', to: '' })
    expect(to).toHaveValue('')
    expect(to).not.toHaveAttribute('aria-invalid')
  })
  it('в тот же день «по» раньше «с» временем: invalid, наружу только день', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host time initial={{ from: '2026-09-10T10:00', to: '' }} onValue={onValue} />)
    const to = screen.getByRole('textbox', { name: 'Дата документа, по' })
    await u.type(to, '100920260900')
    expect(to).toHaveAttribute('aria-invalid', 'true')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10T10:00', to: '2026-09-10' })
    await u.clear(to)
    await u.type(to, '100920261100')
    expect(to).not.toHaveAttribute('aria-invalid')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10T10:00', to: '2026-09-10T11:00' })
  })
  it('в поповере время «по» раньше «с» того же дня — invalid, без времени наружу; сдвиг «с» срезает время «по»', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host time initial={{ from: '2026-09-10T10:00', to: '2026-09-10' }} onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    const tTo = screen.getByRole('textbox', { name: 'Время по' })
    await u.type(tTo, '0900')
    expect(tTo).toHaveAttribute('aria-invalid', 'true')
    expect(onValue).not.toHaveBeenCalled()
    await u.clear(tTo)
    await u.type(tTo, '1200')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10T10:00', to: '2026-09-10T12:00' })
    const tFrom = screen.getByRole('textbox', { name: 'Время с' })
    await u.clear(tFrom)
    await u.type(tFrom, '1300')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10T13:00', to: '2026-09-10' })
  })
  it('со временем пресет оставляет поповер открытым и переводит календарь на его месяц', async () => {
    const u = userEvent.setup()
    renderK(<Host time />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    expect(screen.getByRole('grid', { name: 'Сентябрь 2026' })).toBeInTheDocument()
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Прошлый месяц' }))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    expect(screen.getByRole('grid', { name: 'Август 2026' })).toBeInTheDocument()
  })
  it('клики календаря сохраняют время «с»', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host time initial={{ from: '2026-09-01T09:30', to: '2026-09-02T18:00' }} onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(screen.getByRole('button', { name: /^10 сентября/ }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10T09:30', to: '' })
    await u.click(screen.getByRole('button', { name: /^12 сентября/ }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10T09:30', to: '2026-09-12' })
  })
  it('toDisabled: «по» недоступно, день календаря ставит только «с» и закрывает; многодневные пресеты недоступны', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host toDisabled onValue={onValue} />)
    expect(screen.getByRole('textbox', { name: 'Дата документа, по' })).toBeDisabled()
    expect(screen.getByRole('textbox', { name: 'Дата документа, с' })).toBeEnabled()
    expect(screen.getByRole('button', { name: 'Сегодня' })).toBeEnabled()
    expect(screen.getByRole('button', { name: '3 дня' })).toBeDisabled()
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    expect(within(screen.getByRole('dialog')).getByRole('button', { name: 'Прошлый месяц' })).toBeDisabled()
    await u.click(screen.getByRole('button', { name: /^10 сентября/ }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10', to: '' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
  it('toDisabled: «по» не остаётся скрытым — «Сегодня» и новый «с» дают to пустым; кнопка отмечена и снимается', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host toDisabled onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Сегодня' }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-23', to: '' })
    expect(screen.getByRole('button', { name: 'Сегодня' })).toHaveAttribute('aria-pressed', 'true')
    const from = screen.getByRole('textbox', { name: 'Дата документа, с' })
    await u.clear(from)
    await u.type(from, '10092026')
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10', to: '' })
    expect(onValue.mock.calls.every(([v]) => (v as DateRangeValue).to === '')).toBe(true)
    await u.click(screen.getByRole('button', { name: 'Вчера' }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-22', to: '' })
    await u.click(screen.getByRole('button', { name: 'Вчера' }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '', to: '' })
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Сегодня' }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-23', to: '' })
  })
  it('toDisabled со временем: день календаря не закрывает поповер — можно вписать время «с»; «Готово» закрывает', async () => {
    const u = userEvent.setup()
    const onValue = vi.fn()
    renderK(<Host toDisabled time onValue={onValue} />)
    await u.click(screen.getByRole('button', { name: 'Выбрать период' }))
    await u.click(screen.getByRole('button', { name: /^10 сентября/ }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-10', to: '' })
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: 'Время с' })).toBeEnabled()
    expect(screen.getByRole('textbox', { name: 'Время по' })).toBeDisabled()
    await u.click(screen.getByRole('button', { name: /^12 сентября/ }))
    expect(onValue).toHaveBeenLastCalledWith({ from: '2026-09-12', to: '' })
    await u.click(screen.getByRole('button', { name: 'Готово' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
})
